package frames;

import com.bankroute.datatools.SQLInteraction;
import com.bankroute.user.User;

import static javax.swing.JOptionPane.*;

import java.util.Vector;

import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valentin
 */
public class LoginFrame extends javax.swing.JFrame {

	/**
	 * Creates new form LoginFrame
	 */
	SQLInteraction sQLInteraction = null;
	static final int customerRole = 1;
	static final int bankerRole =2;
	
	public LoginFrame(SQLInteraction sQLInteraction) {
		this.sQLInteraction = sQLInteraction;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		UserNameLabel = new javax.swing.JLabel();
		PasswordLabel = new javax.swing.JLabel();
		ConnectButton = new javax.swing.JButton();
		UserNameImput = new javax.swing.JTextField();
		PasswordImput = new javax.swing.JPasswordField();
		ApllicationNameLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		UserNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		UserNameLabel.setText("UserName");

		PasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		PasswordLabel.setText("Password");

		ConnectButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		ConnectButton.setText("Connect");
		ConnectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConnectButtonActionPerformed(evt);
			}
		}); 

		UserNameImput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		UserNameImput.setName("UserNameImput"); // NOI18N

		PasswordImput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		PasswordImput.setName("PasswordImput"); // NOI18N

		ApllicationNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		ApllicationNameLabel.setText("Bankrupt");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(91, 91, 91)
												.addComponent(UserNameLabel).addGap(18, 18, 18))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup().addContainerGap()
														.addComponent(PasswordLabel).addGap(38, 38, 38)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(UserNameImput, javax.swing.GroupLayout.DEFAULT_SIZE, 167,
												Short.MAX_VALUE)
										.addComponent(PasswordImput)))
						.addGroup(layout.createSequentialGroup().addGap(162, 162, 162)
								.addComponent(ApllicationNameLabel)))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 135, Short.MAX_VALUE).addComponent(ConnectButton,
								javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(116, 116, 116)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(ApllicationNameLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(UserNameImput, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(UserNameLabel))
						.addGap(14, 14, 14)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(PasswordImput, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(PasswordLabel))
						.addGap(43, 43, 43).addComponent(ConnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(35, 35, 35)));

		UserNameImput.getAccessibleContext().setAccessibleName("");
		UserNameImput.getAccessibleContext().setAccessibleDescription("");
		PasswordImput.getAccessibleContext().setAccessibleName("PasswordImput");

		pack();
	}// </editor-fold>

	private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println(UserNameImput.getText().isEmpty() + " | " + PasswordImput.getText().isEmpty());
		if (UserNameImput.getText().isEmpty() && PasswordImput.getText().isEmpty()) {
			showMessageDialog(null, "Username and password empty", "Warning", WARNING_MESSAGE);
		} else if (PasswordImput.getText().isEmpty()) {
			showMessageDialog(null, "Paswword empty", "Warning", WARNING_MESSAGE);
		} else if (UserNameImput.getText().isEmpty()) {
			showMessageDialog(null, "Username empty", "Title", WARNING_MESSAGE);
		} else {
			System.out.println(
					"Role of user: " + sQLInteraction.connectUser(UserNameImput.getText(), PasswordImput.getText()));
			User currentUser = sQLInteraction.connectUser(UserNameImput.getText(), PasswordImput.getText());
			if (currentUser != null) {
				switch (currentUser.getRole()) {
					case bankerRole: 
						UserViewFrame userViewFrame=new UserViewFrame(currentUser);
						userViewFrame.setVisible(true);
						this.setVisible(false);
						break;	
				}
			}

		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel ApllicationNameLabel;
	private javax.swing.JButton ConnectButton;
	private javax.swing.JPasswordField PasswordImput;
	private javax.swing.JLabel PasswordLabel;
	private javax.swing.JTextField UserNameImput;
	private javax.swing.JLabel UserNameLabel;
	// End of variables declaration
}
