package frames;

import com.bankroute.datatools.SQLInteraction;
import com.bankroute.user.Customer;
import com.bankroute.user.User;

import static javax.swing.JOptionPane.*;

import java.awt.EventQueue;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valentin
 */
public class LoginFrame extends javax.swing.JFrame {

	/**
	 * Creates new form LoginFrame
	 */
	SQLInteraction sQLInteraction = null;
	static final int customerRole = 1;
	static final int bankerRole = 2;

	public LoginFrame(SQLInteraction sQLInteraction) {
		this.sQLInteraction = sQLInteraction;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		UserNameLabel = new javax.swing.JLabel();
		PasswordLabel = new javax.swing.JLabel();
		ConnectButton = new javax.swing.JButton();
		UserNameImput = new javax.swing.JTextField();
		PasswordImput = new javax.swing.JPasswordField();
		ApllicationNameLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		UserNameLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
		UserNameLabel.setText("Utilisateur");

		PasswordLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
		PasswordLabel.setText("Mot de passe");

		ConnectButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		ConnectButton.setText("Connexion");
		ConnectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConnectButtonActionPerformed(evt);
			}
		});

		UserNameImput.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
		UserNameImput.setName("UserNameImput"); // NOI18N

		PasswordImput.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
		PasswordImput.setName("PasswordImput"); // NOI18N

		ApllicationNameLabel.setFont(new Font("Tahoma", Font.BOLD, 26)); // NOI18N
		ApllicationNameLabel.setText("Bankrupt");
		
		JButton newUserButton = new JButton("Nouveau Client");
		newUserButton.setFont(new Font("Tahoma", Font.PLAIN, 24));
		newUserButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newUserButtonClicked(evt);
			}
		});
		GroupLayout groupLayout = new GroupLayout(getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(39)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(groupLayout.createSequentialGroup()
							.addComponent(PasswordLabel)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(PasswordImput, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))
						.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
							.addComponent(UserNameLabel)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(ApllicationNameLabel)
								.addComponent(UserNameImput, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))))
					.addGap(46))
				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
					.addContainerGap(132, Short.MAX_VALUE)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(newUserButton, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
						.addComponent(ConnectButton, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE))
					.addGap(112))
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(ApllicationNameLabel)
					.addGap(36)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(UserNameLabel)
						.addComponent(UserNameImput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(PasswordLabel)
						.addComponent(PasswordImput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addComponent(ConnectButton, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(newUserButton, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
					.addGap(18))
		);
		getContentPane().setLayout(groupLayout);

		UserNameImput.getAccessibleContext().setAccessibleName("");
		UserNameImput.getAccessibleContext().setAccessibleDescription("");
		PasswordImput.getAccessibleContext().setAccessibleName("PasswordImput");
		setBounds(100, 100, 587, 404);
		pack();
	}// </editor-fold>

	
	//						.addComponent(newUserButton, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE))

	private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println(UserNameImput.getText().isEmpty() + " | " + PasswordImput.getText().isEmpty());
		if (UserNameImput.getText().isEmpty() && PasswordImput.getText().isEmpty()) {
			showMessageDialog(null, "Username and password empty", "Warning", WARNING_MESSAGE);
		} else if (PasswordImput.getText().isEmpty()) {
			showMessageDialog(null, "Paswword empty", "Warning", WARNING_MESSAGE);
		} else if (UserNameImput.getText().isEmpty()) {
			showMessageDialog(null, "Username empty", "Title", WARNING_MESSAGE);
		} else {
			System.out.println(
					"Role of user: " + sQLInteraction.connectUser(UserNameImput.getText(), PasswordImput.getText()));
			User currentUser = sQLInteraction.connectUser(UserNameImput.getText(), PasswordImput.getText());
			UserInterfaceFrame userInterfaceFrame = new UserInterfaceFrame(currentUser);
			userInterfaceFrame.setVisible(true);
			dispose();
		}
	}
	
	private void newUserButtonClicked(ActionEvent evt) {
		UserDetailsFrame newUserFrame= new UserDetailsFrame(sQLInteraction);
		newUserFrame.setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JLabel ApllicationNameLabel;
	private javax.swing.JButton ConnectButton;
	private javax.swing.JPasswordField PasswordImput;
	private javax.swing.JLabel PasswordLabel;
	private javax.swing.JTextField UserNameImput;
	private javax.swing.JLabel UserNameLabel;
}