package frames;

import com.bankrupt.datatools.SQLInteraction;
import com.bankrupt.user.Customer;
import com.bankrupt.user.User;

import static javax.swing.JOptionPane.*;

import java.awt.EventQueue;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valentin
 */
public class LoginFrame extends javax.swing.JFrame {

	/**
	 * Creates new form LoginFrame
	 */
	SQLInteraction sQLInteraction = null;
	static final int customerRole = 1;
	static final int bankerRole = 2;

	public LoginFrame(SQLInteraction sQLInteraction) {
		setResizable(false);
		this.sQLInteraction = sQLInteraction;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		UserNameLabel = new javax.swing.JLabel();
		PasswordLabel = new javax.swing.JLabel();
		ConnectButton = new javax.swing.JButton();
		UserNameInput = new javax.swing.JTextField();
		PasswordInput = new javax.swing.JPasswordField();
		ApllicationNameLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		UserNameLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
		UserNameLabel.setText("Utilisateur");
		
		PasswordLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
		PasswordLabel.setText("Mot de passe");

		ConnectButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		ConnectButton.setText("Connexion");
		ConnectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConnectButtonActionPerformed(evt);
			}
		});

		UserNameInput.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
		UserNameInput.setName("UserNameInput"); // NOI18N
		UserNameInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConnectButtonActionPerformed(evt);
			}
		});

		PasswordInput.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
		PasswordInput.setName("PasswordInput"); // NOI18N
		PasswordInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConnectButtonActionPerformed(evt);
			}
		});

		ApllicationNameLabel.setFont(new Font("Tahoma", Font.BOLD, 26)); // NOI18N
		ApllicationNameLabel.setText("Bankrupt");
		
		JButton newUserButton = new JButton("Nouveau Client");
		newUserButton.setFont(new Font("Tahoma", Font.PLAIN, 24));
		newUserButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newUserButtonClicked(evt);
			}
		});
		GroupLayout groupLayout = new GroupLayout(getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(39)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(groupLayout.createSequentialGroup()
							.addComponent(PasswordLabel)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(PasswordInput, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))
						.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
							.addComponent(UserNameLabel)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(ApllicationNameLabel)
								.addComponent(UserNameInput, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))))
					.addGap(46))
				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
					.addContainerGap(132, Short.MAX_VALUE)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(newUserButton, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
						.addComponent(ConnectButton, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE))
					.addGap(112))
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(ApllicationNameLabel)
					.addGap(36)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(UserNameLabel)
						.addComponent(UserNameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(PasswordLabel)
						.addComponent(PasswordInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addComponent(ConnectButton, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(newUserButton, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
					.addGap(18))
		);
		getContentPane().setLayout(groupLayout);

		UserNameInput.getAccessibleContext().setAccessibleName("");
		UserNameInput.getAccessibleContext().setAccessibleDescription("");
		PasswordInput.getAccessibleContext().setAccessibleName("PasswordInput");
		setBounds(100, 100, 587, 404);
		pack();
	}// </editor-fold>

	
	//						.addComponent(newUserButton, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE))

	private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {
		
		try {
			System.out.println(UserNameInput.getText().isEmpty() + " | " + PasswordInput.getText().isEmpty());
			if (UserNameInput.getText().isEmpty() && PasswordInput.getText().isEmpty()) {
				showMessageDialog(null, "Nom d'utilisateur et mot de passe vides", "Warning", WARNING_MESSAGE);
			} else if (PasswordInput.getText().isEmpty()) {
				showMessageDialog(null, "Mot de passe vide", "Warning", WARNING_MESSAGE);
			} else if (UserNameInput.getText().isEmpty()) {
				showMessageDialog(null, "Utilisateur vide", "Title", WARNING_MESSAGE);
			} else {
				System.out.println(
						"Role of user: " + sQLInteraction.connectUser(UserNameInput.getText(), PasswordInput.getText()));
				User currentUser = sQLInteraction.connectUser(UserNameInput.getText(), PasswordInput.getText());
				UserInterfaceFrame userInterfaceFrame = new UserInterfaceFrame(currentUser, sQLInteraction);
				userInterfaceFrame.setVisible(true);
				dispose();
			}
		} catch (Exception e)
		{
			System.out.println(e.toString());
			showMessageDialog(null, "Impossible de se connecter. Merci de vérifier les informations saisies", "Warning", WARNING_MESSAGE);
		}
	}
	
	private void newUserButtonClicked(ActionEvent evt) {
		UserDetailsFrame newUserFrame= new UserDetailsFrame(sQLInteraction);
		newUserFrame.setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JLabel ApllicationNameLabel;
	private javax.swing.JButton ConnectButton;
	private javax.swing.JPasswordField PasswordInput;
	private javax.swing.JLabel PasswordLabel;
	private javax.swing.JTextField UserNameInput;
	private javax.swing.JLabel UserNameLabel;
}